title: County-level broadband access from 2010 to 2014
subtitle: Benjamin Skinner
baseurl: ""
github: https://github.com/btskinner/broadband
mail: btskinner@virginia.edu

date_format: "%d %B %Y"

google_analytics: UA-63981025-1
disqus_shortname:

# Build settings
permalink:    pretty


